import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n
  .use(initReactI18next)
  .init({
    resources: {
      en: {
        translation: {
          welcome: 'AgroConnect Mitr',
          tagline: 'Jobs & Workers for Agriculture',
          findJobs: 'Find Jobs',
          searchJobs: 'Search jobs by name or place...',
          noJobs: 'No jobs found.',
          findWorkers: 'Find Workers',
          searchWorkers: 'Search workers by name or skills...',
          noWorkers: 'No workers found.',
          jobTitle: 'Job',
          location: 'Location',
          wage: 'Wage',
          about: 'About',
          skills: 'Skills Needed',
          posted: 'Posted',
          status: 'Your Status',
          close: 'Close',
          apply: 'Apply',
          login: 'Login',
          help: 'Help',
          home: 'Home',
          jobs: 'Jobs',
          worker: 'Workers',
          farmer: 'Farmer',
          confirmApply: 'Confirm your application for',
          yes: 'Yes',
          no: 'No',
         contactTitle: 'Contact Us',
        yourName: 'Your Name',
        yourEmail: 'Your Email',
        subject: 'Subject',
        message: 'Your Message',
        sendMessage: 'Send Message',
        contactSuccess: 'Your message has been sent successfully!',
        contactError: 'Failed to send your message. Please try again.',
          helpTitle: 'Help & Support',
          faqSection: 'Frequently Asked Questions',
          faq1: 'How to apply for a job? Click on job listing and use "Apply" button.',
          faq2: 'How to contact support? Use the contact form below.',
          guideSection: 'Quick Guide',
          guide1: 'Register as a Farmer or Worker to get started.',
          guide2: 'Search for jobs or workers on the main page.',
          guide3: 'Login to apply or post jobs.',
          contactSupport: 'Contact Support',
          'Your Name': 'Your Name',
          messageSent: 'Message sent successfully!',
          paymentDetailsTitle: 'Payment Details',
          enterUPI: 'Enter your UPI ID',
          showUPI: 'Show UPI',
          upiVisible: 'Your UPI is visible: {{upi}}',
          targetUPI: 'Target UPI: {{upi}}',
          farmerUPI: 'Farmer UPI',
          workerUPI: 'Worker UPI',
          amountToPay: 'Amount to Pay',
          uploadScreenshot: 'Upload Screenshot',
          screenshotPlaceholder: 'Upload payment screenshot...',
          upload: 'Upload',
          screenshotUploaded: 'Screenshot uploaded successfully!',
          selectImage: 'Select Image',
          scanQR: 'Scan QR Code',
          qrScanner: 'QR Scanner'
        },
      },
      hi: {
        translation: {
          welcome: 'एग्रोकनेक्ट मित्र',
          tagline: 'कृषि के लिए नौकरियाँ और श्रमिक',
          findJobs: 'नौकरियाँ ढूँढें',
          searchJobs: 'नाम या स्थान से नौकरियाँ खोजें...',
          noJobs: 'कोई नौकरी नहीं मिली।',
          findWorkers: 'श्रमिक ढूँढें',
          searchWorkers: 'नाम या कौशल से श्रमिक खोजें...',
          noWorkers: 'कोई श्रमिक नहीं मिला।',
          jobTitle: 'नौकरी',
          location: 'स्थान',
          wage: 'मजदूरी',
          about: 'बारे में',
          skills: 'आवश्यक कौशल',
          posted: 'पोस्ट किया गया',
          status: 'आपकी स्थिति',
          close: 'बंद करें',
          apply: 'आवेदन करें',
          login: 'लॉगिन',
          help: 'सहायता',
          home: 'होम',
          jobs: 'नौकरियाँ',
          worker: 'श्रमिक',
          farmer: 'किसान',
          confirmApply: '"{selectedJob.title}" के लिए अपना आवेदन पुष्टि करें',
          yes: 'हां',
          no: 'नहीं',
          contactTitle: 'हमसे संपर्क करें',
        yourName: 'आपका नाम',
        yourEmail: 'आपका ईमेल',
        subject: 'विषय',
        message: 'आपका संदेश',
        sendMessage: 'संदेश भेजें',
        contactSuccess: 'आपका संदेश सफलतापूर्वक भेज दिया गया है!',
        contactError: 'संदेश भेजने में विफल रहा। कृपया पुनः प्रयास करें।',
          helpTitle: 'सहायता और समर्थन',
          faqSection: 'सामान्य प्रश्न',
          faq1: 'नौकरी के लिए कैसे आवेदन करें? नौकरी की सूची पर क्लिक करें और \'आवेदन करें\' बटन का उपयोग करें।',
          faq2: 'समर्थन से कैसे संपर्क करें? नीचे दिए गए संपर्क फॉर्म का उपयोग करें।',
          guideSection: 'त्वरित मार्गदर्शिका',
          guide1: 'शुरुआत करने के लिए किसान या श्रमिक के रूप में पंजीकरण करें।',
          guide2: 'मुख्य पृष्ठ पर नौकरियों या श्रमिकों की खोज करें।',
          guide3: 'लॉगिन करके आवेदन करें या नौकरियां पोस्ट करें।',
          contactSupport: 'समर्थन से संपर्क करें',
          'Your Name': 'आपका नाम',
          messageSent: 'संदेश सफलतापूर्वक भेजा गया!',
          paymentDetailsTitle: 'भुगतान विवरण',
          enterUPI: 'अपना UPI ID दर्ज करें',
          showUPI: 'UPI दिखाएं',
          upiVisible: 'आपका UPI दिखाई दे रहा है: {{upi}}',
          targetUPI: 'लक्ष्य UPI: {{upi}}',
          farmerUPI: 'किसान UPI',
          workerUPI: 'मजदूर UPI',
          amountToPay: 'भुगतान की जाने वाली राशि',
          uploadScreenshot: 'स्क्रीनशॉट अपलोड करें',
          screenshotPlaceholder: 'भुगतान स्क्रीनशॉट अपलोड करें...',
          upload: 'अपलोड करें',
          screenshotUploaded: 'स्क्रीनशॉट सफलतापूर्वक अपलोड किया गया!',
          selectImage: 'छवि चुनें',
          scanQR: 'QR कोड स्कैन करें',
          qrScanner: 'QR स्कैनर'
        },
      },
      mr: {
        translation: {
          welcome: 'अ‍ॅग्रोकनेक्ट मित्र',
          tagline: 'शेतीसाठी नोकरी आणि कामगार',
          findJobs: 'नोकऱ्या शोधा',
          searchJobs: 'नाव किंवा ठिकाणावरून नोकऱ्या शोधा...',
          noJobs: 'कोणत्याही नोकऱ्या आढळल्या नाहीत.',
          findWorkers: 'कामगार शोधा',
          searchWorkers: 'नाव किंवा कौशल्यानुसार कामगार शोधा...',
          noWorkers: 'कोणताही कामगार आढळला नाही.',
          jobTitle: 'नोकरी',
          location: 'स्थान',
          wage: 'मजुरी',
          about: 'बद्दल',
          skills: 'आवश्यक कौशल्ये',
          posted: 'पोस्ट केले',
          status: 'तुमची स्थिती',
          close: 'बंद करा',
          apply: 'अर्ज करा',
          login: 'लॉगिन करा',
          help: 'मदत',
          home: 'मुख्यपृष्ठ',
          jobs: 'नोकऱ्या',
          worker: 'कामगार',
          farmer: 'शेतकरी',
          confirmApply: '"{selectedJob.title}" साठी तुमचा अर्ज निश्चित करा',
          yes: 'होय',
          no: 'नाही',
          contactTitle: 'आमच्याशी संपर्क साधा',
        yourName: 'तुमचे नाव',
        yourEmail: 'तुमचा ईमेल',
        subject: 'विषय',
        message: 'तुमचे संदेश',
        sendMessage: 'संदेश पाठवा',
        contactSuccess: 'तुमचा संदेश यशस्वीरित्या पाठवला गेला आहे!',
        contactError: 'तुमचा संदेश पाठवणे अपयशी ठरले. कृपया पुन्हा प्रयत्न करा.',
          helpTitle: 'मदत आणि समर्थन',
          faqSection: 'वारंवार विचारले जाणारे प्रश्न',
          faq1: 'नोकरीसाठी अर्ज कसा करावा? नोकरीच्या सूचीवर क्लिक करा आणि "अर्ज करा" बटण वापरा.',
          faq2: 'समर्थनाशी कसे संपर्क साधावे? खालील संपर्क फॉर्म वापरा.',
          guideSection: 'त्वरित मार्गदर्शक',
          guide1: 'सुरुवात करण्यासाठी शेतकरी किंवा कामगार म्हणून नोंदणी करा.',
          guide2: 'मुख्यपृष्ठावर नोकऱ्या किंवा कामगार शोधा.',
          guide3: 'अर्ज करण्यासाठी किंवा नोकऱ्या पोस्ट करण्यासाठी लॉगिन करा.',
          contactSupport: 'समर्थनाशी संपर्क साधा',
          'Your Name': 'तुमचे नाव',
          messageSent: 'संदेश यशस्वीरित्या पाठवला गेला!',
          paymentDetailsTitle: 'पेमेंट तपशील',
          enterUPI: 'तुमचा UPI आयडी एंटर करा',
          showUPI: 'UPI दाखवा',
          upiVisible: 'तुमचा UPI दिसत आहे: {{upi}}',
          targetUPI: 'लक्ष्य UPI: {{upi}}',
          farmerUPI: 'शेतकरी UPI',
          workerUPI: 'कामगार UPI',
          amountToPay: 'देय रक्कम',
          uploadScreenshot: 'स्क्रीनशॉट अपलोड करा',
          screenshotPlaceholder: 'पेमेंट स्क्रीनशॉट अपलोड करा...',
          upload: 'अपलोड करा',
          screenshotUploaded: 'स्क्रीनशॉट यशस्वीरित्या अपलोड केला!',
          selectImage: 'प्रतिमा निवडा',
          scanQR: 'QR कोड स्कॅन करा',
          qrScanner: 'QR स्कॅनर'
        },
      },
    },
    lng: 'en', // default language
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false, // react already escapes by default
    },
  });

export default i18n;

// import i18n from 'i18next';
// import { initReactI18next } from 'react-i18next';

// i18n
//   .use(initReactI18next)
//   .init({
//     resources: {
//       en: {
//         translation: {
//           welcome: 'AgroConnect Mitr',
//           tagline: 'Jobs & Workers for Agriculture',
//           findJobs: 'Find Jobs',
//           searchJobs: 'Search jobs by name or place...',
//           noJobs: 'No jobs found.',
//           findWorkers: 'Find Workers',
//           searchWorkers: 'Search workers by name or skills...',
//           noWorkers: 'No workers found.',
//           jobTitle: 'Job',
//           location: 'Location',
//           wage: 'Wage',
//           about: 'About',
//           skills: 'Skills Needed',
//           posted: 'Posted',
//           status: 'Your Status',
//           close: 'Close',
//           apply: 'Apply',
//           login: 'Login',
//           help: 'Help',
//           home: 'Home',
//           jobs: 'Jobs',
//           worker: 'Workers',
//           farmer: 'Farmer',
//           confirmApply: 'Confirm your application for',
//           yes: 'Yes',
//           no: 'No',
//           contactTitle: 'Contact Us',
//           yourName: 'Your Name',
//           yourEmail: 'Your Email',
//           subject: 'Subject',
//           message: 'Message',
//           sendMessage: 'Send message',
//           helpTitle: 'Help & Support',
//           faqSection: 'Frequently Asked Questions',
//           faq1: 'How to apply for a job? Click on a job listing and use the \'Apply\' button.',
//           faq2: 'How to contact support? Use the contact form below.',
//           guideSection: 'Quick Guide',
//           guide1: 'Register as a farmer or worker to get started.',
//           guide2: 'Explore jobs or workers on the home page.',
//           guide3: 'Log in to apply or post jobs.',
//           contactSupport: 'Contact Support',
//           "Your Name": 'Your Name',
//           messageSent: 'Message sent successfully!',
//           paymentDetailsTitle: 'Payment Details',
//           enterUPI: 'Enter your UPI ID',
//           showUPI: 'Show UPI',
//           upiVisible: 'Your UPI is visible: {{upi}}',
//           targetUPI: 'Target UPI: {{upi}}',
//           farmerUPI: 'Farmer UPI',
//           workerUPI: 'Worker UPI',
//         }
//       },        translation: {
//           welcome: 'अॅग्रोकोनेक्ट मित्र',
//           tagline: 'शेतीसाठी नोकऱ्या आणि कामगार',
//           findJobs: 'नोकऱ्या शोधा',
//           searchJobs: 'नाव किंवा ठिकाणानुसार नोकऱ्या शोधा...',
//           noJobs: 'नोकऱ्या सापडल्या नाहीत.',
//           findWorkers: 'कामगार शोधा',
//           searchWorkers: 'नाव किंवा कौशल्यानुसार कामगार शोधा...',
//           noWorkers: 'कामगार सापडले नाहीत.',
//           jobTitle: 'नोकरी',
//           location: 'ठिकाण',
//           wage: 'पगार',
//           about: 'माहिती',
//           skills: 'आवश्यक कौशल्ये',
//           posted: 'प्रकाशित',
//           status: 'तुमची स्थिती',
//           close: 'बंद करा',
//           apply: 'कामासाठी अर्ज करा',
//           login: 'लॉगिन',
//           help: 'मदत',
//           home: 'मुख्यपृष्ठ',
//           jobs: 'नोकऱ्या',
//           worker: 'कामगार',
//           farmer: 'शेतकरी',
//           confirmApply: 'प्रो "{selectedJob.title}" साठी तुमचा अर्ज पुष्टी करा',
//           yes: 'होय',
//           no: 'नाही',
//           contactTitle: 'आमच्याशी संपर्क साधा',
//           yourName: 'तुमचे नाव',
//           yourEmail: 'तुमचा ईमेल',
//           subject: 'विषय',
//           message: 'संदेश',
//           sendMessage: 'संदेश पाठवा',
//           helpTitle: 'मदत आणि समर्थन',
//           faqSection: 'वारंवार विचारले जाणारे प्रश्न',
//           faq1: 'नोकरीसाठी कसा अर्ज करावा? नोकरीच्या यादीवर क्लिक करा आणि \'अर्ज करा\' बटणाचा वापर करा.',
//           faq2: 'समर्थनाशी कसा संपर्क साधावा? खालील संपर्क फॉर्म वापरा.',
//           guideSection: 'त्वरित मार्गदर्शक',
//           guide1: 'शेतकरी किंवा कामगार म्हणून नोंदणी करा सुरूवात करण्यासाठी.',
//           guide2: 'मुख्य पृष्ठावर नोकऱ्या किंवा कामगारांचा शोध घ्या.',
//           guide3: 'लॉगिन करून अर्ज करा किंवा नोकऱ्या पोस्ट करा.',
//           contactSupport: 'समर्थनाशी संपर्क साधा',
//           messageSent: 'संदेश यशस्वीपणे पाठवला!',
//          paymentDetailsTitle: 'पेमेंट तपशील',
//           enterUPI: 'आपला UPI ID प्रविष्ट करा',
//           showUPI: 'UPI दर्शवा',
//           upiVisible: 'आपला UPI दृश्यमान आहे: {{upi}}',
//           targetUPI: 'लक्ष्य UPI: {{upi}}',
//           farmerUPI: 'शेतकरी UPI',
//           workerUPI: 'कामगार UPI',
//         }
//       },
//       hi: {
//         translation: {
//           welcome: 'अग्रोकोनेक्ट मित्र',
//           tagline: 'कृषि के लिए नौकरियां और श्रमिक',
//           findJobs: 'नौकरियां खोजें',
//           searchJobs: 'नाम या स्थान के अनुसार नौकरियां खोजें...',
//           noJobs: 'कोई नौकरियां नहीं मिलीं.',
//           findWorkers: 'श्रमिक खोजें',
//           searchWorkers: 'नाम या कौशल के अनुसार श्रमिक खोजें...',
//           noWorkers: 'कोई श्रमिक नहीं मिले.',
//           jobTitle: 'नौकरी',
//           location: 'स्थान',
//           wage: 'वेतन',
//           about: 'जानकारी',
//           skills: 'आवश्यक कौशल',
//           posted: 'प्रकाशित',
//           status: 'आपकी स्थिति',
//           close: 'बंद करें',
//           apply: 'आवेदन करें',
//           login: 'लॉगिन',
//           help: 'सहायता',
//           home: 'होम',
//           jobs: 'नौकरियां',
//           worker: 'श्रमिक',
//           farmer: 'किसान',
//           confirmApply: '"{selectedJob.title}" के लिए अपना आवेदन पुष्टि करें',
//           yes: 'हां',
//           no: 'नहीं',
//           contactTitle: 'हमसे संपर्क करें',
//           yourName: 'आपका नाम',
//           yourEmail: 'आपका ईमेल',
//           subject: 'विषय',
//           message: 'संदेश',
//           sendMessage: 'संदेश भेजें',
//           helpTitle: 'सहायता और समर्थन',
//           faqSection: 'सामान्य प्रश्न',
//           faq1: 'नौकरी के लिए कैसे आवेदन करें? नौकरी की सूची पर क्लिक करें और \'आवेदन करें\' बटन का उपयोग करें।',
//           faq2: 'समर्थन से कैसे संपर्क करें? नीचे दिए गए संपर्क फॉर्म का उपयोग करें।',
//           guideSection: 'त्वरित मार्गदर्शिका',
//           guide1: 'शुरुआत करने के लिए किसान या श्रमिक के रूप में पंजीकरण करें।',
//           guide2: 'मुख्य पृष्ठ पर नौकरियों या श्रमिकों की खोज करें।',
//           guide3: 'लॉगिन करके आवेदन करें या नौकरियां पोस्ट करें।',
//           contactSupport: 'समर्थन से संपर्क करें',
//           'Your Name': 'आपका नाम',
//           messageSent: 'संदेश सफलतापूर्वक भेजा गया!',
//           paymentDetailsTitle: 'भुगतान विवरण',
//           enterUPI: 'अपना UPI ID दर्ज करें',
//           showUPI: 'UPI दिखाएं',
//           upiVisible: 'आपका UPI दिखाई दे रहा है: {{upi}}',
//           targetUPI: 'लक्ष्य UPI: {{upi}}',
//           farmerUPI: 'किसान UPI',
//           workerUPI: 'मजदूर UPI',
//         }
//       }
//     },
//     lng: 'en',
//     fallbackLng: 'en',
//     interpolation: { escapeValue: false }
//   });

// export default i18n;